# https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization#configuring-the-l10n-yaml-file
arb-dir: assets/translations
output-dir: lib/core/configs/.gen
template-arb-file: app_ko.arb
output-localization-file: app_localization.g.dart
output-class: AppLocalization
# flutter_gen plugin error fix
synthetic-package: false
